version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smk_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: smk_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: smk_db
      MYSQL_USER: smk_user
      MYSQL_PASSWORD: smk_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

